<a href="https://colab.research.google.com/github/FilipeSCampos/Analise-de-Dados/blob/main/futbolanalise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROVA A2
## Utilizando as URLs abaixo faça o que é pedido em cada trecho de código. 
## Serão avaliados se os comando implementados por vocês irá gerar os resultados esperados.

##Tabelas a serem utilizadas
###url_terra = 'https://www.cbf.com.br/futebol-brasileiro/competicoes/campeonato-brasileiro-serie-a/2022'

###url_cnn = 'https://www.cnnbrasil.com.br/esporte/futebol/tabela-brasileirao-serie-a-2022/'

In [ ]:
# importe a biblioteca do pandas
import pandas as pd

In [ ]:
#utilizando a url do site terra, transforme as informações em um dataframe
url_terra = 'https://www.cbf.com.br/futebol-brasileiro/competicoes/campeonato-brasileiro-serie-a/2022'

html_terra = pd.read_html(url_terra)
tabelaterra = html_terra[0]
display(tabelaterra)

,Posição,PTS,J,V,E,D,GP,GC,SG,CA,CV,%,Recentes,Próx
0,1º 0 Palmeiras - SP,81,38,23,12,3,66,27,39,85,6,71,E V D,NaN
1,2º 0 Internacional - RS,73,38,20,13,5,58,31,27,94,5,64,V V V,NaN
2,3º 0 Fluminense - RJ,70,38,21,7,10,63,41,22,85,11,61,V V V,NaN
3,4º 0 Corinthians - SP,65,38,18,11,9,44,36,8,84,6,57,V E D,NaN
4,5º 0 Flamengo - RJ,62,38,18,8,12,60,39,21,84,4,54,D E D,NaN
5,6º 0 Athletico Paranaense - PR,58,38,16,10,12,48,48,0,95,4,50,D E V,NaN
6,7º 0 Atlético Mineiro - MG,58,38,15,13,10,45,37,8,93,3,50,D V V,NaN
7,8º +1 Fortaleza - CE,55,38,15,10,13,46,39,7,88,8,48,E V V,NaN
8,9º +4 São Paulo - SP,54,38,13,15,10,55,42,13,102,9,47,D D V,NaN
9,10º -2 América Fc Saf - MG,53,38,15,8,15,40,40,0,88,5,46,V D E,NaN
10,11º -1 Botafogo - RJ,53,38,15,8,15,41,43,-2,98,6,46,V V D,NaN
11,12º -1 Santos - SP,47,38,12,11,15,44,41,3,102,7,41,E D D,NaN
12,13º -1 Goiás - GO,46,38,11,13,14,40,53,-13,117,8,40,V D D,NaN
13,14º 0 Red Bull Bragantino - SP,44,38,11,11,16,49,59,-10,93,7,38,D D D,NaN
14,15º 0 Coritiba - PR,42,38,12,6,20,39,60,-21,113,12,36,V E D,NaN
15,16º +1 Cuiabá Saf - MT,41,38,10,11,17,31,42,-11,82,11,35,E D V,NaN
16,17º -1 Ceará - CE,37,38,7,16,15,34,41,-7,127,10,32,D D V,NaN
17,18º +1 Atlético - GO,36,38,8,12,18,39,57,-18,104,9,31,E E E,NaN
18,19º -1 Avaí - SC,35,38,9,8,21,34,60,-26,102,4,30,E V V,NaN
19,20º 0 Juventude - RS,22,38,3,13,22,29,69,-40,112,8,19,D E D,NaN

In [ ]:
#utilizando a url do site da cnn, transforme as informações em um dataframe
url_cnn = 'https://www.cnnbrasil.com.br/esporte/futebol/tabela-brasileirao-serie-a-2022/'

html_cnn = pd.read_html(url_cnn)
tabelacnn = html_cnn[0]
display(tabelacnn)

                   Classificação   p   j   v   e   d   g  gc  sg
0              1  Palmeiras  PAL  81  38  23  12   3  66  27  39
1          2  Internacional  INT  73  38  20  13   5  58  31  27
2             3  Fluminense  FLU  70  38  21   7  10  63  41  22
3            4  Corinthians  COR  65  38  18  11   9  44  36   8
4               5  Flamengo  FLA  62  38  18   8  12  60  39  21
5           6  Athletico-PR  CAP  58  38  16  10  12  48  48   0
6            7  Atlético-MG  CAM  58  38  15  13  10  45  37   8
7              8  Fortaleza  FOR  55  38  15  10  13  46  39   7
8              9  São Paulo  SAO  54  38  13  15  10  55  42  13
9            10  América-MG  AMG  53  38  15   8  15  40  40   0
10             11  Botafogo  BOT  53  38  15   8  15  41  43  -2
11               12  Santos  SAN  47  38  12  11  15  44  41   3
12                13  Goiás  GOI  46  38  11  13  14  40  53 -13
13  14  Red Bull Bragantino  RBB  44  38  11  11  16  49  59 -10
14             15  Coritiba  CFC  42  38  12   6  20  39  60 -21
15               16  Cuiabá  CUI  41  38  10  11  17  31  42 -11
16                17  Ceará  CEA  37  38   7  16  15  34  41  -7
17          18  Atlético-GO  AGO  36  38   8  12  18  39  57 -18
18                 19  Avaí  AVA  35  38   9   8  21  34  60 -26
19            20  Juventude  ECJ  22  38   3  13  22  29  69 -40

In [ ]:
#junte os dois dataframe criados em um novo dataframe chamado dt_final
dt_final = pd.concat([tabelaterra,tabelacnn],axis=1)
display(dt_final)

,Posição,PTS,J,V,E,D,GP,GC,SG,CA,...,Próx,Classificação,p,j,v,e,d,g,gc,sg
0,1º 0 Palmeiras - SP,81,38,23,12,3,66,27,39,85,...,NaN,1 Palmeiras PAL,81,38,23,12,3,66,27,39
1,2º 0 Internacional - RS,73,38,20,13,5,58,31,27,94,...,NaN,2 Internacional INT,73,38,20,13,5,58,31,27
2,3º 0 Fluminense - RJ,70,38,21,7,10,63,41,22,85,...,NaN,3 Fluminense FLU,70,38,21,7,10,63,41,22
3,4º 0 Corinthians - SP,65,38,18,11,9,44,36,8,84,...,NaN,4 Corinthians COR,65,38,18,11,9,44,36,8
4,5º 0 Flamengo - RJ,62,38,18,8,12,60,39,21,84,...,NaN,5 Flamengo FLA,62,38,18,8,12,60,39,21
5,6º 0 Athletico Paranaense - PR,58,38,16,10,12,48,48,0,95,...,NaN,6 Athletico-PR CAP,58,38,16,10,12,48,48,0
6,7º 0 Atlético Mineiro - MG,58,38,15,13,10,45,37,8,93,...,NaN,7 Atlético-MG CAM,58,38,15,13,10,45,37,8
7,8º +1 Fortaleza - CE,55,38,15,10,13,46,39,7,88,...,NaN,8 Fortaleza FOR,55,38,15,10,13,46,39,7
8,9º +4 São Paulo - SP,54,38,13,15,10,55,42,13,102,...,NaN,9 São Paulo SAO,54,38,13,15,10,55,42,13
9,10º -2 América Fc Saf - MG,53,38,15,8,15,40,40,0,88,...,NaN,10 América-MG AMG,53,38,15,8,15,40,40,0
10,11º -1 Botafogo - RJ,53,38,15,8,15,41,43,-2,98,...,NaN,11 Botafogo BOT,53,38,15,8,15,41,43,-2
11,12º -1 Santos - SP,47,38,12,11,15,44,41,3,102,...,NaN,12 Santos SAN,47,38,12,11,15,44,41,3
12,13º -1 Goiás - GO,46,38,11,13,14,40,53,-13,117,...,NaN,13 Goiás GOI,46,38,11,13,14,40,53,-13
13,14º 0 Red Bull Bragantino - SP,44,38,11,11,16,49,59,-10,93,...,NaN,14 Red Bull Bragantino RBB,44,38,11,11,16,49,59,-10
14,15º 0 Coritiba - PR,42,38,12,6,20,39,60,-21,113,...,NaN,15 Coritiba CFC,42,38,12,6,20,39,60,-21
15,16º +1 Cuiabá Saf - MT,41,38,10,11,17,31,42,-11,82,...,NaN,16 Cuiabá CUI,41,38,10,11,17,31,42,-11
16,17º -1 Ceará - CE,37,38,7,16,15,34,41,-7,127,...,NaN,17 Ceará CEA,37,38,7,16,15,34,41,-7
17,18º +1 Atlético - GO,36,38,8,12,18,39,57,-18,104,...,NaN,18 Atlético-GO AGO,36,38,8,12,18,39,57,-18
18,19º -1 Avaí - SC,35,38,9,8,21,34,60,-26,102,...,NaN,19 Avaí AVA,35,38,9,8,21,34,60,-26
19,20º 0 Juventude - RS,22,38,3,13,22,29,69,-40,112,...,NaN,20 Juventude ECJ,22,38,3,13,22,29,69,-40

In [ ]:
#Neste momento responda:
#Quantas linhas e colunas tem o dataframe criado pela junção? Coloque o comando utilizado para saber os valores aqui
print(dt_final.shape)
# 20 linhas e 23 colunas

(20, 23)

In [ ]:
# Remova as colunas do dt_final com os seguintes nomes ['Classificação', 'PTS', 'j', 'V', 'e', 'd', 'g','GC', 'SG', 'Próx', '%', 'Recentes', 'CV']
dt_final2 = dt_final.drop(['Classificação', 'PTS', 'j', 'V', 'e', 'd', 'g','GC', 'SG', 'Próx', '%', 'Recentes', 'CV'],axis = 1)
display(dt_final2)

                             Posição   J   E   D  GP   CA   p   v  gc  sg
0              1º  0  Palmeiras - SP  38  12   3  66   85  81  23  27  39
1          2º  0  Internacional - RS  38  13   5  58   94  73  20  31  27
2             3º  0  Fluminense - RJ  38   7  10  63   85  70  21  41  22
3            4º  0  Corinthians - SP  38  11   9  44   84  65  18  36   8
4               5º  0  Flamengo - RJ  38   8  12  60   84  62  18  39  21
5   6º  0  Athletico Paranaense - PR  38  10  12  48   95  58  16  48   0
6       7º  0  Atlético Mineiro - MG  38  13  10  45   93  58  15  37   8
7             8º  +1  Fortaleza - CE  38  10  13  46   88  55  15  39   7
8             9º  +4  São Paulo - SP  38  15  10  55  102  54  13  42  13
9       10º  -2  América Fc Saf - MG  38   8  15  40   88  53  15  40   0
10            11º  -1  Botafogo - RJ  38   8  15  41   98  53  15  43  -2
11              12º  -1  Santos - SP  38  11  15  44  102  47  12  41   3
12               13º  -1  Goiás - GO  38  13  14  40  117  46  11  53 -13
13  14º  0  Red Bull Bragantino - SP  38  11  16  49   93  44  11  59 -10
14             15º  0  Coritiba - PR  38   6  20  39  113  42  12  60 -21
15          16º  +1  Cuiabá Saf - MT  38  11  17  31   82  41  10  42 -11
16               17º  -1  Ceará - CE  38  16  15  34  127  37   7  41  -7
17            18º  +1  Atlético - GO  38  12  18  39  104  36   8  57 -18
18                19º  -1  Avaí - SC  38   8  21  34  102  35   9  60 -26
19            20º  0  Juventude - RS  38  13  22  29  112  22   3  69 -40

In [ ]:
# apague os seguintes times do dt_final
# ['20º 0 Juventude - RS', '19º -1 Avaí - SC', '18º -2 Ceará - CE', 17º +2 Atlético - GO]
# podem usar os indices [16,17,18,19]
dt_final2 = dt_final2.drop([16,17,18,19],axis = 0)
dt_final2

                             Posição   J   E   D  GP   CA   p   v  gc  sg
0              1º  0  Palmeiras - SP  38  12   3  66   85  81  23  27  39
1          2º  0  Internacional - RS  38  13   5  58   94  73  20  31  27
2             3º  0  Fluminense - RJ  38   7  10  63   85  70  21  41  22
3            4º  0  Corinthians - SP  38  11   9  44   84  65  18  36   8
4               5º  0  Flamengo - RJ  38   8  12  60   84  62  18  39  21
5   6º  0  Athletico Paranaense - PR  38  10  12  48   95  58  16  48   0
6       7º  0  Atlético Mineiro - MG  38  13  10  45   93  58  15  37   8
7             8º  +1  Fortaleza - CE  38  10  13  46   88  55  15  39   7
8             9º  +4  São Paulo - SP  38  15  10  55  102  54  13  42  13
9       10º  -2  América Fc Saf - MG  38   8  15  40   88  53  15  40   0
10            11º  -1  Botafogo - RJ  38   8  15  41   98  53  15  43  -2
11              12º  -1  Santos - SP  38  11  15  44  102  47  12  41   3
12               13º  -1  Goiás - GO  38  13  14  40  117  46  11  53 -13
13  14º  0  Red Bull Bragantino - SP  38  11  16  49   93  44  11  59 -10
14             15º  0  Coritiba - PR  38   6  20  39  113  42  12  60 -21
15          16º  +1  Cuiabá Saf - MT  38  11  17  31   82  41  10  42 -11

In [ ]:
# adicione os seguintes times no dataframe (Cruzeiro, Gremio, Bahia e Vasco)
# coloque todos eles com a pontuação (coluna p) = 35
# o restante das informações numéricas devem ter o valor = 37
# ex: {'Posição' : '17º +1 CRUZEIRO',	'J' : 37,	'E' : 37,	'D' : 37,	'GP' : 37,	'CA' : 37,	'p' : 35,	'v' : 37,	'gc' : 37,	'sg' : 37}
dt_final2 = dt_final2.append({'Posição' : '17º +1 CRUZEIRO',	'J' : 37,	'E' : 37,	'D' : 37,	'GP' : 37,	'CA' : 37,	'p' : 35,	'v' : 37,	'gc' : 37,	'sg' : 37},ignore_index=True)
dt_final2 = dt_final2.append({'Posição' : '18º +1 GREMIO',	'J' : 37,	'E' : 37,	'D' : 37,	'GP' : 37,	'CA' : 37,	'p' : 35,	'v' : 37,	'gc' : 37,	'sg' : 37},ignore_index=True)
dt_final2 = dt_final2.append({'Posição' : '19º +1 BAHIA',	'J' : 37,	'E' : 37,	'D' : 37,	'GP' : 37,	'CA' : 37,	'p' : 35,	'v' : 37,	'gc' : 37,	'sg' : 37},ignore_index=True)
dt_final2 = dt_final2.append({'Posição' : '20º +1 VASCO',	'J' : 37,	'E' : 37,	'D' : 37,	'GP' : 37,	'CA' : 37,	'p' : 35,	'v' : 37,	'gc' : 37,	'sg' : 37},ignore_index=True)
dt_final2

                             Posição   J   E   D  GP   CA   p   v  gc  sg
0              1º  0  Palmeiras - SP  38  12   3  66   85  81  23  27  39
1          2º  0  Internacional - RS  38  13   5  58   94  73  20  31  27
2             3º  0  Fluminense - RJ  38   7  10  63   85  70  21  41  22
3            4º  0  Corinthians - SP  38  11   9  44   84  65  18  36   8
4               5º  0  Flamengo - RJ  38   8  12  60   84  62  18  39  21
5   6º  0  Athletico Paranaense - PR  38  10  12  48   95  58  16  48   0
6       7º  0  Atlético Mineiro - MG  38  13  10  45   93  58  15  37   8
7             8º  +1  Fortaleza - CE  38  10  13  46   88  55  15  39   7
8             9º  +4  São Paulo - SP  38  15  10  55  102  54  13  42  13
9       10º  -2  América Fc Saf - MG  38   8  15  40   88  53  15  40   0
10            11º  -1  Botafogo - RJ  38   8  15  41   98  53  15  43  -2
11              12º  -1  Santos - SP  38  11  15  44  102  47  12  41   3
12               13º  -1  Goiás - GO  38  13  14  40  117  46  11  53 -13
13  14º  0  Red Bull Bragantino - SP  38  11  16  49   93  44  11  59 -10
14             15º  0  Coritiba - PR  38   6  20  39  113  42  12  60 -21
15          16º  +1  Cuiabá Saf - MT  38  11  17  31   82  41  10  42 -11
16                   17º +1 CRUZEIRO  37  37  37  37   37  35  37  37  37
17                     18º +1 GREMIO  37  37  37  37   37  35  37  37  37
18                      19º +1 BAHIA  37  37  37  37   37  35  37  37  37
19                      20º +1 VASCO  37  37  37  37   37  35  37  37  37

## Tendo o resultado acima, responda os seguintes questionamentos:

### 1 - Quais os times com menos de 42 pontos? 
### 2 - Quais os times com 15 vitórias e mais de 52 pontos? 
### 3 - Quais os times com sg menor que 0? 
### 4 - Quantos times tem menos de 10 derrotas?

In [ ]:
# coloque o código para responder a q1 aqui:
pontos = dt_final2.loc[dt_final2['p'] < 42,['Posição','p']]
pontos

                     Posição   p
15  16º  +1  Cuiabá Saf - MT  41
16           17º +1 CRUZEIRO  35
17             18º +1 GREMIO  35
18              19º +1 BAHIA  35
19              20º +1 VASCO  35

In [ ]:
# coloque o código para responder a q2 aqui:
vitorias = dt_final2.loc[dt_final2['v'] == 15,['Posição','p','v']]
vitorias

                         Posição   p   v
6   7º  0  Atlético Mineiro - MG  58  15
7         8º  +1  Fortaleza - CE  55  15
9   10º  -2  América Fc Saf - MG  53  15
10        11º  -1  Botafogo - RJ  53  15

In [ ]:
# coloque o código para responder a q3 aqui:
sg = dt_final2.loc[dt_final2['sg'] < 0,['Posição','sg']]
sg

                             Posição  sg
10            11º  -1  Botafogo - RJ  -2
12               13º  -1  Goiás - GO -13
13  14º  0  Red Bull Bragantino - SP -10
14             15º  0  Coritiba - PR -21
15          16º  +1  Cuiabá Saf - MT -11

In [ ]:
# coloque o código para responder a q4 aqui:
derrota = dt_final2.loc[dt_final2['D'] < 10,['Posição','D']]
derrota

                     Posição  D
0      1º  0  Palmeiras - SP  3
1  2º  0  Internacional - RS  5
3    4º  0  Corinthians - SP  9